#!/bin/bash

python -m ipykernel install --name elastixenv
python -m ipykernel install --name elastixenv2
python -m ipykernel install --name itktestenvdebug

# jupyter labextension install @jupyter-widgets/jupyterlab-manager@2.0.0 --dev-build=False --minimize=False
# jupyter labextension install jupyter-matplotlib jupyterlab-datawidgets itkwidgets --dev-build=False --minimize=False
