name: Notebook tests

on: [push, pull_request]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          SHA=$(echo "${GITHUB_SHA}" | cut -c1-12)
          docker run alextreebeard/itkelastix:${SHA} pytest -n=auto --nbmake examples