name: Notebook tests

on: [push, pull_request]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: jupyterhub/repo2docker-action@master
      #   with:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  test_nbs:
    runs-on: ubuntu-latest
    needs: [build_image]
    steps:
      - run: pwd
      - run: ls -la
      - run: docker run alextreebeard/itkelastix:latest pytest --nbmake examples/*ipynb